### ISSUE TITLE
Command ESPCMD_MKDIR always creates directory in root folder

### ISSUE THREAD

**Issue by RevCurtisP** [fvdhoef/aquarius-plus#22] opened 2023-08-17 03:15 UTC
MKDIR "test
CD "test
MKDIR "subdir

Directory is created in '/' instead of '/test"

Happens on hardware and in emulator

**Comment by fvdhoef** [comment] 2023-08-17 04:57
Duplicate of #20. Already fixed in master branch. Will be part of next release build.

**Closed by fvdhoef** 2023-08-17 04:57 UTC
